# https://docs.cilium.io/en/stable/helm-reference/

hubble:
  enabled: true
  dashboards:
    enabled: true
    namespace: cilium-monitoring
    annotations:
      grafana_folder: "Hubble"
  prometheus:
    enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
    # - dns:query;ignoreAAAA
    - dns
    - drop #:sourceContext=identity;destinationContext=identity
    - tcp
    - flow
    - icmp
    - port-distribution
    - 'httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity'
  relay:
    enabled: true
  ui:
    enabled: true

image:
  pullPolicy: IfNotPresent

ipam:
  mode: kubernetes

kubeProxyReplacement: true

operator:
  prometheus:
    enabled: true

prometheus:
  enabled: true

############################## Cilium with Istio ##############################
# Cilium must ensure traffic redirected to Istio is not disrupted
socketLB:
  hostNamespaceOnly: true
# Cilium CNI must not interfere with Istio CNI plugin (which implements both 
# sidecar and ambient modes)
cni:
  exclusive: false
# hostServices:
#   hostNamespaceOnly: true
