kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Single master node: don't elect ETCD leader
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    controllerManager:
      extraArgs:
        leader-elect: "false"
    scheduler:
      extraArgs:
        leader-elect: "false"
- role: worker
- role: worker
networking:
  # Don't install kind CNI (kindnet)
  disableDefaultCNI: true
  # Don't run kube-proxy
  kubeProxyMode: none
  podSubnet: "10.0.0.0/16"
  serviceSubnet: "10.1.0.0/16"